"""Merge a LoRA adapter into the base weights, producing a standalone model.

Evaluation loads models by path, so an adapter has to be folded in first:
    W_merged = W + (alpha/r) * B @ A

Merging rather than serving the adapter at runtime keeps every eval condition
an ordinary model behind one identical code path, so "all conditions were
generated by the same harness with the same decoding settings" stays true
without qualification.

Costs ~3.5GB of disk per condition, which is the price of that simplicity.

    python -m training.merge_adapter --adapter outputs/dpo_lr5e-6 \\
        --out models/dpo_lr5e-6
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import torch
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer

BASE_MODEL = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--adapter", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--base", default=BASE_MODEL)
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    config_path = args.adapter / "adapter_config.json"
    if not config_path.exists():
        raise FileNotFoundError(f"no adapter_config.json in {args.adapter}")
    adapter_config = json.loads(config_path.read_text())

    # The adapter is only valid against the base it was trained on; loading a
    # mismatched pair would silently produce a differently-behaved model.
    trained_on = adapter_config.get("base_model_name_or_path")
    if trained_on and trained_on != args.base:
        raise ValueError(f"adapter was trained on {trained_on}, not {args.base}")

    print(f"base    {args.base}")
    print(f"adapter {args.adapter}  r={adapter_config.get('r')} "
          f"alpha={adapter_config.get('lora_alpha')}")

    model = AutoModelForCausalLM.from_pretrained(args.base, dtype=torch.bfloat16)
    model = PeftModel.from_pretrained(model, str(args.adapter))
    # Folds (alpha/r)*BA into W and returns the plain base architecture, so the
    # result loads in vLLM with no LoRA support required.
    model = model.merge_and_unload()

    args.out.mkdir(parents=True, exist_ok=True)
    model.save_pretrained(str(args.out))
    # The tokenizer travels with the model: eval applies the chat template from
    # whatever it loads, and a missing one would silently fall back to the base.
    AutoTokenizer.from_pretrained(args.base).save_pretrained(str(args.out))

    print(f"\nmerged -> {args.out}")


if __name__ == "__main__":
    main()
